### ISSUE TITLE
aliyun oss + 你这个sdk ，是否对springboot3支持

### ISSUE THREAD

**Issue by esbug** [dromara/x-file-storage#162]
我在启动类加上@EnableFileStorage注解，会报以下错误，查了一下，应该是springboot版本导致的：

```
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/web/servlet/config/annotation/WebMvcConfigurer.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:211) ~[spring-core-6.0.11.jar:6.0.11]
	at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:54) ~[spring-core-6.0.11.jar:6.0.11]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:48) ~[spring-core-6.0.11.jar:6.0.11]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[spring-core-6.0.11.jar:6.0.11]
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:86) ~[spring-boot-3.1.3.jar:3.1.3]
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:73) ~[spring-boot-3.1.3.jar:3.1.3]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81) ~[spring-core-6.0.11.jar:6.0.11]
	at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:610) ~[spring-context-6.0.11.jar:6.0.11]
	at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getInterfaces(ConfigurationClassParser.java:936) ~[spring-context-6.0.11.jar:6.0.11]
	at org.springframework.context.annotation.ConfigurationClassParser.processInterfaces(ConfigurationClassParser.java:379) ~[spring-context-6.0.11.jar:6.0.11]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:325) ~[spring-context-6.0.11.jar:6.0.11]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:243) ~[spring-context-6.0.11.jar:6.0.11]
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:514) ~[spring-context-6.0.11.jar:6.0.11]
```

有什么解决方案吗？

**Comment by 1171736840** [comment]
支持SpringBoot3，你这样应该没引入SpringWEB 导致的，当前dev分支已解决这个问题，下个版本发布，目前可以参考这里解决：https://github.com/dromara/x-file-storage/issues/155

**Comment by esbug** [comment]
> 支持SpringBoot3，你这样应该没导入SpringWEB导致的，当前dev分支已解决这个问题，下个版本发布，目前可以参考这里解决：#155

好的，感谢您的回答，期待下一个版本。我自己也通过自己的方式解决了这个问题。
![image](https://github.com/dromara/x-file-storage/assets/39432059/09a72ab9-4f46-43d1-a340-375a160e1a29)

1.我把x-file-spring里面的代码复制了一份出来，去掉了WebMvcConfigurer相关的，因为我这里用不到本地存储，所以移除对我没影响。
2.然后springboot启动类，启用我复制出来的那一个@EnableFileStorage，所有问题都得到解决，并且我所需的fileStorageService的基本功能都调用正常。
