### ISSUE TITLE
直接上传报错

### ISSUE THREAD

**Issue by rowstop** [dromara/x-file-storage#227]
```log
2024-03-05 15:05:51.111 ERROR 1 --- [  XNIO-1 task-3] io.undertow.request                      : UT005023: Exception handling request to /oss/upload

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.dromara.x.file.storage.core.exception.FileStorageRuntimeException: 文件上传失败！platform：smart-shop.png，filename：TENCENT
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:182)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at com.medusa.gruul.common.system.model.filter.SystemFilter.doFilter(SystemFilter.java:83)
        at com.medusa.gruul.common.system.model.filter.AbstractServletFilter.doFilter(AbstractServletFilter.java:25)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.dromara.x.file.storage.core.exception.FileStorageRuntimeException: 文件上传失败！platform：smart-shop.png，filename：TENCENT
        at org.dromara.x.file.storage.core.exception.ExceptionFactory.upload(ExceptionFactory.java:70)
        at org.dromara.x.file.storage.core.platform.TencentCosFileStorage.save(TencentCosFileStorage.java:152)
        at org.dromara.x.file.storage.core.upload.UploadActuator.lambda$execute$0(UploadActuator.java:104)
        at org.dromara.x.file.storage.core.aspect.UploadAspectChain.next(UploadAspectChain.java:34)
        at org.dromara.x.file.storage.core.upload.UploadActuator.execute(UploadActuator.java:112)
        at org.dromara.x.file.storage.core.upload.UploadActuator.execute(UploadActuator.java:44)
        at org.dromara.x.file.storage.core.upload.UploadPretreatment.upload(UploadPretreatment.java:1028)
        at com.medusa.gruul.carrier.pigeon.service.modules.oss.controller.OssController.upload(OssController.java:74)
        at com.medusa.gruul.carrier.pigeon.service.modules.oss.controller.OssController$$FastClassBySpringCGLIB$$8bf77463.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.medusa.gruul.carrier.pigeon.service.modules.oss.controller.OssController$$EnhancerBySpringCGLIB$$b8f35dcf.upload(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        ... 99 common frames omitted
Caused by: com.qcloud.cos.exception.CosClientException: httpClient execute occur a unknown exception. httpRequest: endpoint: medusa-small-file-1253272780.cos.ap-shanghai.myqcloud.com, resourcepath: /gruul/2024/03/05/65e6c44fe4b0dd23ccec8f73.png, httpMethod: PUT, headers { Authorization : q-sign-algorithm=sha1&q-ak=AKIDnRzNc9Bqy19b0rMXdbVZUJ3e3GKIinCR&q-sign-time=1709622351;1709625951&q-key-time=1709622351;1709625951&q-header-list=content-type&q-url-param-list=&q-signature=dc9aff3d6f9d2d3d099f4b8c49d3b2435655b957, User-Agent : cos-java-sdk-v5.6.19/Linux/jdk-17.0.2/OpenJDK 64-Bit Server VM, Host : medusa-small-file-1253272780.cos.ap-shanghai.myqcloud.com, Content-Length : 14296, Content-Type : image/jpeg, }, params: { }
        at com.qcloud.cos.http.DefaultCosHttpClient.exeute(DefaultCosHttpClient.java:432)
        at com.qcloud.cos.COSClient.invoke(COSClient.java:575)
        at com.qcloud.cos.COSClient.uploadObjectInternal(COSClient.java:937)
        at com.qcloud.cos.COSClient.putObject(COSClient.java:780)
        at org.dromara.x.file.storage.core.platform.TencentCosFileStorage.save(TencentCosFileStorage.java:127)
        ... 128 common frames omitted
Caused by: com.qcloud.cos.exception.CosClientException: More data read than expected: dataLength=14342; expectedLength=14296; includeSkipped=false; in.getClass()=class com.qcloud.cos.internal.ReleasableInputStream; markedSupported=false; marked=0; resetSinceLastMarked=false; markCount=0; resetCount=0
        at com.qcloud.cos.internal.LengthCheckInputStream.checkLength(LengthCheckInputStream.java:135)
        at com.qcloud.cos.internal.LengthCheckInputStream.read(LengthCheckInputStream.java:94)
        at com.qcloud.cos.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:65)
        at com.qcloud.cos.internal.MD5DigestCalculatingInputStream.read(MD5DigestCalculatingInputStream.java:100)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
        at com.qcloud.cos.internal.SdkBufferedInputStream.read(SdkBufferedInputStream.java:64)
        at com.qcloud.cos.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:65)
        at com.qcloud.cos.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:65)
        at com.qcloud.cos.event.ProgressInputStream.read(ProgressInputStream.java:163)
        at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:140)
        at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:121)
        at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
        at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152)
        at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.qcloud.cos.http.DefaultCosHttpClient.exeute(DefaultCosHttpClient.java:404)
        ... 132 common frames omitted
```

**Comment by 1171736840** [comment]
提供配置文件、依赖版本、上传代码

**Comment by 1171736840** [comment]
上传代码

**Comment by 1171736840** [comment]
配

**Comment by 1171736840** [comment]
置

**Comment by 1171736840** [comment]
件

**Comment by 1171736840** [comment]
还

**Comment by 1171736840** [comment]
有

**Comment by 1171736840** [comment]
依

**Comment by 1171736840** [comment]
赖

**Comment by 1171736840** [comment]
版

**Comment by 1171736840** [comment]
本

**Comment by rowstop** [comment]
动态添加的配置，配置文件只配置了这个，你是要腾讯云
```java
@Override
    public void afterPropertiesSet() {
        //从 redis、数据库种查询 oss 配置
        Map<StorageType, ? extends StorageConf> storageTypeMap = ossConfService.allConf();
        if (MapUtil.isEmpty(storageTypeMap)) {
            return;
        }
        //获得存储平台 List
        CopyOnWriteArrayList<FileStorage> storages = fileStorageService.getFileStorageList();
        storageTypeMap.forEach(
                (type, conf) -> {
                    //添加新的存储配置
                    List<? extends FileStorage> newCurrentStorages = type.getConvert().apply(type, conf);
                    storages.addAll(newCurrentStorages);
                }
        );
        String defaultPlatform = RedisUtil.getCacheObject(OssConstant.OSS_DEFAULT_KEY);
        //如果缓存的平台为空则取第一个存储配置的平台
        if (StrUtil.isEmpty(defaultPlatform)) {
            defaultPlatform = storages.get(0).getPlatform();
        }
        fileStorageService.getProperties().setDefaultPlatform(defaultPlatform);

    }
```

**Comment by 1171736840** [comment]
腾讯云依赖版本多少，是否与文档一致？

**Comment by rowstop** [comment]
这什么 你在，发这么多干啥

**Comment by 1171736840** [comment]
啥？

**Comment by rowstop** [comment]
> 腾讯云依赖版本多少，是否与文档一致？

我去检查下

**Comment by rowstop** [comment]
> servlet.multipart.resolve-lazily: true

好

**Comment by rowstop** [comment]
那什么这种方式是可以的
![image](https://github.com/dromara/x-file-storage/assets/100893704/0a084a80-e704-4c4a-8c48-72bc17ae4dc5)

**Comment by 1171736840** [comment]
那就可能是你的代码在某处读取了 HttpServletRequest 中的参数导致的，或者上传时没按照要求传参数，比如文件参数必须是最后一个

**Comment by rowstop** [comment]
只有一个参数 file

**Comment by 1171736840** [comment]
那就传一下吧，可能你那边提交过来的请求头体格式不是太标准，导致文件大小推断错误

**Comment by rowstop** [comment]
哎 哥 看看我的pr

**Comment by 1171736840** [comment]
小问题，等我有空合并

**Comment by 1171736840** [comment]
> > 那就传一下吧，可能你那边提交过来的请求头体格式不是太标准，导致文件大小推断错误
> 
> 不知道哎，貌似不管什么文件size都只少46

你试试用Postman上传应该没问题的，你是用什么工具传的？

**Comment by rowstop** [comment]
> > > 那就传一下吧，可能你那边提交过来的请求头体格式不是太标准，导致文件大小推断错误
> > 
> > 
> > 不知道哎，貌似不管什么文件size都只少46
> 
> 你试试用Postman上传应该没问题的，你是用什么工具传的？

javascript

**Comment by rowstop** [comment]
[curl.txt](https://github.com/dromara/x-file-storage/files/14492688/curl.txt)
