### ISSUE TITLE
没有找到对应的存储平台

### ISSUE THREAD

**Issue by jiaqingzii** [dromara/x-file-storage#308]
救救，依赖什么的都是复制官网文档的，为啥还是找不到对应的存储平台嘞？感觉大家都没有这个问题，依赖整好就能启动。
- 报错信息：

`org.dromara.x.file.storage.core.exception.FileStorageRuntimeException:` 没有找到对应的存储平台！platform:null
	at org.dromara.x.file.storage.core.FileStorageService.getFileStorageVerify(FileStorageService.java:100)
	at org.dromara.x.file.storage.core.get.GetFileActuator.execute(GetFileActuator.java:27)
	at org.dromara.x.file.storage.core.get.GetFilePretreatment.getFile(GetFilePretreatment.java:98)
	at org.dromara.x.file.storage.core.FileStorageService.getFile(FileStorageService.java:542)
	at org.gandong.monitorplatform.service.MonitorService.downloadDatafile(MonitorService.java:92)
	at org.gandong.monitorplatform.service.MonitorServiceTest.downloadDatafile(MonitorServiceTest.java:37)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at `java.base/java.util.ArrayList.forEach(ArrayList.java:1511)`
![image](https://github.com/user-attachments/assets/93db9b6d-8e9c-4c3f-8f9f-0d7e6f16e342)

- pom 文件（Spring 版本为 3.4，JDK 17，maven 3.8）：
![image](https://github.com/user-attachments/assets/e5bdea59-c0c8-428c-8c34-5e49b301eb53)

![image](https://github.com/user-attachments/assets/502f70ee-ef20-4a40-a7b6-6ad2a717a78f)

- 配置文件：
![image](https://github.com/user-attachments/assets/1b10c606-a70b-4056-a443-65b25c37a4c5)

- 获取文件方法：
![image](https://github.com/user-attachments/assets/a6c351b9-5315-4ef0-8979-aa5204de0c0d)
- 测试类
![image](https://github.com/user-attachments/assets/8daa3d0f-ce20-4a03-b54d-10c0cb5cbba6)

**Comment by jiaqingzii** [comment]
- 主类也加注解了

![image](https://github.com/user-attachments/assets/ea2feec0-341a-460d-bf47-096966e1b753)

**Comment by jiaqingzii** [comment]
重启电脑，好了
