### ISSUE TITLE
升级solon3.0.5启动报错

### ISSUE THREAD

**Issue by qq229338869** [dromara/x-file-storage#313]
升级solon3.0.5启动报错，报错信息如下：
```java
java.lang.IllegalStateException: AppContext start failed
	at org.noear.solon.core.AppContext.start(AppContext.java:1066)
	at org.noear.solon.SolonApp.run(SolonApp.java:314)
	at org.noear.solon.SolonApp.startDo(SolonApp.java:166)
	at org.noear.solon.Solon.start(Solon.java:193)
	at org.noear.solon.Solon.start(Solon.java:153)
	at org.noear.solon.Solon.start(Solon.java:130)
	at org.solon.lz_solon_start.App.main(App.java:9)
Caused by: java.lang.IllegalStateException: Build bean of method failed: public org.dromara.x.file.storage.core.tika.TikaFactory org.dromara.x.file.storage.solon.FileStorageAutoConfiguration.tikaFactory()
	at org.noear.solon.core.AppContext.tryBuildBeanOfMethod2(AppContext.java:879)
	at org.noear.solon.core.AppContext.tryBuildBeanOfMethod1(AppContext.java:791)
	at org.noear.solon.core.AppContext.tryBuildBeanOfMethod0(AppContext.java:777)
	at org.noear.solon.core.AppContext.tryBuildBeanOfMethod(AppContext.java:754)
	at org.noear.solon.core.AppContext.lambda$initialize$2(AppContext.java:195)
	at org.noear.solon.core.AppContext.tryBuildBeanOfClass3(AppContext.java:979)
	at org.noear.solon.core.AppContext.tryBuildBeanOfClass2(AppContext.java:963)
	at org.noear.solon.core.AppContext.tryBuildBeanOfClass1(AppContext.java:937)
	at org.noear.solon.core.AppContext.tryBuildBeanOfClass0(AppContext.java:912)
	at org.noear.solon.core.AppContext.lambda$tryBuildBeanOfClass$18(AppContext.java:895)
	at org.noear.solon.core.AppContext.startBeanLifecycle(AppContext.java:1080)
	at org.noear.solon.core.AppContext.start(AppContext.java:1058)
	... 6 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Build bean of method failed: public org.dromara.x.file.storage.core.tika.ContentTypeDetect org.dromara.x.file.storage.solon.FileStorageAutoConfiguration.contentTypeDetect(org.dromara.x.file.storage.core.tika.TikaFactory)
	at org.noear.solon.core.InjectGather.run(InjectGather.java:112)
	at org.noear.solon.core.wrap.VarHolderOfParam.setValue(VarHolderOfParam.java:134)
	at org.noear.solon.core.BeanContainer.lambda$beanInjectDo$19(BeanContainer.java:973)
	at org.noear.solon.core.BeanContainer.beanHashPublish(BeanContainer.java:406)
	at org.noear.solon.core.BeanContainer.putWrap(BeanContainer.java:512)
	at org.noear.solon.core.BeanContainer.beanRegisterSupI(BeanContainer.java:882)
	at org.noear.solon.core.BeanContainer.beanRegister(BeanContainer.java:864)
	at org.noear.solon.core.AppContext.tryBuildBeanOfMethod2(AppContext.java:868)
	... 17 common frames omitted
Caused by: java.lang.IllegalStateException: Build bean of method failed: public org.dromara.x.file.storage.core.tika.ContentTypeDetect org.dromara.x.file.storage.solon.FileStorageAutoConfiguration.contentTypeDetect(org.dromara.x.file.storage.core.tika.TikaFactory)
	at org.noear.solon.core.AppContext.tryBuildBeanOfMethod2(AppContext.java:879)
	at org.noear.solon.core.AppContext.lambda$null$15(AppContext.java:794)
	at org.noear.solon.core.util.RunUtil.runOrThrow(RunUtil.java:68)
	at org.noear.solon.core.AppContext.lambda$tryBuildBeanOfMethod1$16(AppContext.java:794)
	at org.noear.solon.core.AppContext.lambda$tryMethodParamsGather$17(AppContext.java:806)
	at org.noear.solon.core.InjectGather.run(InjectGather.java:110)
	... 24 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Build bean of method failed: public org.dromara.x.file.storage.core.FileStorageService org.dromara.x.file.storage.solon.FileStorageAutoConfiguration.fileStorageService(org.dromara.x.file.storage.core.recorder.FileRecorder,java.util.List,java.util.List,java.util.List,org.dromara.x.file.storage.core.tika.ContentTypeDetect,java.util.List)
	at org.noear.solon.core.InjectGather.run(InjectGather.java:112)
	at org.noear.solon.core.wrap.VarHolderOfParam.setValue(VarHolderOfParam.java:134)
	at org.noear.solon.core.BeanContainer.lambda$beanInjectDo$19(BeanContainer.java:973)
	at org.noear.solon.core.BeanContainer.beanHashPublish(BeanContainer.java:406)
	at org.noear.solon.core.BeanContainer.putWrap(BeanContainer.java:512)
	at org.noear.solon.core.BeanContainer.beanRegisterSupI(BeanContainer.java:882)
	at org.noear.solon.core.BeanContainer.beanRegister(BeanContainer.java:864)
	at org.noear.solon.core.AppContext.tryBuildBeanOfMethod2(AppContext.java:868)
	... 29 common frames omitted
Caused by: java.lang.IllegalStateException: Build bean of method failed: public org.dromara.x.file.storage.core.FileStorageService org.dromara.x.file.storage.solon.FileStorageAutoConfiguration.fileStorageService(org.dromara.x.file.storage.core.recorder.FileRecorder,java.util.List,java.util.List,java.util.List,org.dromara.x.file.storage.core.tika.ContentTypeDetect,java.util.List)
	at org.noear.solon.core.AppContext.tryBuildBeanOfMethod2(AppContext.java:879)
	at org.noear.solon.core.AppContext.lambda$null$15(AppContext.java:794)
	at org.noear.solon.core.util.RunUtil.runOrThrow(RunUtil.java:68)
	at org.noear.solon.core.AppContext.lambda$tryBuildBeanOfMethod1$16(AppContext.java:794)
	at org.noear.solon.core.AppContext.lambda$tryMethodParamsGather$17(AppContext.java:806)
	at org.noear.solon.core.InjectGather.run(InjectGather.java:110)
	... 36 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "org.dromara.x.file.storage.solon.SolonFileStorageProperties.toFileStorageProperties()" because "this.properties" is null
	at org.dromara.x.file.storage.solon.FileStorageAutoConfiguration.fileStorageService(FileStorageAutoConfiguration.java:97)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.noear.solon.core.wrap.MethodWrap.invoke(MethodWrap.java:269)
	at org.noear.solon.core.AppContext.tryBuildBeanOfMethod2(AppContext.java:828)
	... 41 common frames omitted
```

![f6e62e7609a588a48070fb1dc742926d](https://github.com/user-attachments/assets/bf3c5aae-f848-42b0-a55a-d0e884b9ab49)

这个地方没有执行，可能是3.0.5的bean扫描时机被修改了

**Comment by 1171736840** [comment]
可能吧，我 Solon 不太熟悉，你可以到 Solon 社区问问新版本该怎么写，手动注入应该就行了吧

**Comment by qq229338869** [comment]
感谢
![32bcd9beee16a20dde705dcdff8397d3](https://github.com/user-attachments/assets/03252716-4625-4e6e-a7a1-2c0778d11937)
